packages:
  - packages/*
  - packages/nimiq-icons/dist
  - apps/*
  - docs/
catalog:
  vite: ^6.2.0
  vue: ^3.5.13
  unocss-preset-onmax: ^1.0.0-beta.9
  unocss-preset-fluid-sizing: ^0.0.17
  unocss: ^66.1.0-beta.3
  '@unocss/reset': ^66.1.0-beta.3
  '@unocss/preset-web-fonts': ^66.1.0-beta.3
  '@iconify/utils': ^2.3.0
  typescript: ^5.8.2
  vitest: ^3.0.5
onlyBuiltDependencies:
  - vue-demi
