packages:
  - packages/*
  - packages/nimiq-icons/src
  - apps/*
  - docs/
catalog:
  vite: ^6.2.0
  vue: ^3.5.13
  unocss-preset-onmax: ^1.0.0-beta.13
  unocss-preset-fluid-sizing: ^0.0.17
  unocss: ^66.1.0-beta.5
  '@unocss/reset': ^66.1.0-beta.5
  '@unocss/preset-web-fonts': ^66.1.0-beta.5
  '@iconify/utils': ^2.3.0
  '@nolebase/vitepress-plugin-git-changelog': ^2.15.1
  typescript: ^5.8.2
  vitest: ^3.0.5
  pathe: ^2.0.3
onlyBuiltDependencies:
  - vue-demi
