packages:
  - packages/*
  - packages/nimiq-icons/src/icons
  - packages/nimiq-icons/src/flags
  - apps/*
  - docs/
catalogs:
  build:
    '@nolebase/vitepress-plugin-git-changelog': ^2.17.1
    '@shikijs/vitepress-twoslash': ^3.4.2
    unbuild: ^3.5.0
    unplugin-icons: ^22.1.0
    vite: ^6.3.5
    vite-plugin-inspect: ^11.1.0
    vite-plugin-vue-devtools: ^7.7.6
    vitepress: ^2.0.0-alpha.5
  cli:
    bumpp: ^10.1.1
    pncat: ^0.2.4
  dev:
    '@antfu/ni': ^25.0.0
    jsdom: ^26.1.0
    typescript: ^5.8.3
  frontend:
    reka-ui: ^2.3.0
    vue: ^3.5.15
    vue-router: ^4.5.1
  icons:
    '@iconify-json/simple-icons': ^1.2.36
    '@iconify-json/tabler': ^1.2.18
    '@iconify-json/vscode-icons': ^1.2.21
    '@iconify/tools': ^4.1.2
    '@iconify/types': ^2.0.0
    '@iconify/utils': ^2.3.0
    '@iconify/vue': ^5.0.0
    iconify-icon: ^3.0.0
  lint:
    '@antfu/eslint-config': ^4.13.2
    '@unocss/eslint-config': ^66.1.2
    '@unocss/eslint-plugin': ^66.1.2
    eslint: ^9.27.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.0
    simple-git-hooks: ^2.13.0
  markdown:
    render-markdown-it-tokens: ^0.0.4
  node:
    consola: ^3.4.2
    dotenv: ^16.5.0
    pathe: ^2.0.3
    rimraf: ^6.0.1
  prod:
    colorjs.io: ^0.5.2
    mark.js: ^8.11.1
    minisearch: ^7.1.2
    ts-cssjson: ^3.0.1
    vaul-vue: ^0.4.1
  script:
    esno: ^4.8.0
  style:
    '@unocss/cli': ^66.1.2
    '@unocss/preset-web-fonts': ^66.1.2
    '@unocss/preset-wind4': ^66.1.2
    unocss: ^66.1.2
    unocss-preset-animations: ^1.2.1
    unocss-preset-light-dark: ^1.0.0-beta.30
    unocss-preset-onmax: ^1.0.0-beta.30
  syntax:
    shiki: ^3.4.2
  test:
    vitest: ^3.1.4
  types:
    '@types/jsdom': ^21.1.7
    '@types/markdown-it': ^14.1.2
    '@types/node': ^22.15.23
  utils:
    '@vueuse/core': ^13.3.0
    defu: ^6.1.4
onlyBuiltDependencies:
  - esbuild
  - vue-demi
