name: Deploy Docs & pkg.new

on:
  # Run on pushes but ignore commits from our workflow
  push:
    branches: ['**']
    paths-ignore:
      - 'packages/nimiq-icons/dist/**'  # Ignore changes to the icons dist directory
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

# Cancel in-progress runs when new changes are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Shared build job
  build:
    # Skip if commit message contains [skip ci]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
        env:
          FIGMA_FILE_ID: ${{ secrets.FIGMA_FILE_ID }}
          FIGMA_API_TOKEN: ${{ secrets.FIGMA_API_TOKEN }}

      # Upload entire workspace for subsequent jobs
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            .
            !node_modules
          retention-days: 1

  # VitePress docs deployment job
  deploy-docs:
    needs: build
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Package publishing job
  deploy-pkg:
    needs: build
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref != 'refs/heads/main')
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - uses: pnpm/action-setup@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Release
        run: pnpm dlx pkg-pr-new publish --pnpm './packages/*'

      - name: Update icons
        working-directory: packages/nimiq-icons
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist --force
          git commit -m "Updated icons [skip ci]" || echo "No changes to commit"
          git push || echo "Nothing to push"
